<a href="https://colab.research.google.com/github/ktasha45/sprout-class-2022/blob/master/learn_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# numpy

In [1]:
import numpy as np

In [ ]:
a = np.array([1, 2, 3]) # 3차원 vector
b = np.arange(1, 12, 1)
c = np.arange(1.0, 12.0, 1.0)
d = np.array(range(1, 12, 1))
e = np.array(range(1, 12, 1), dtype=np.float16)

print('a', a)
print(a.dtype)
print()
print('b', b)
print(b.dtype)
print()
print('c', c)
print(c.dtype)
print()
print('d', d)
print(d.dtype)
print()
print('e', e)
print(e.dtype)

In [ ]:
print(c)
c[2] = 123
print(c)

In [ ]:
print(c[:3])
print(c[4:])

In [ ]:
print(a.shape, b.shape, c.shape)

# reshape, index

In [ ]:
a = np.arange(1, 13, 1, dtype=np.float16).reshape((3, 4))
print(a)

In [ ]:
a = np.arange(1, 5, 1, dtype=np.int64).reshape((-1, 1))
print(a)
print(a.shape)

In [ ]:
b = np.zeros((3, 3))
print(b)

In [ ]:
c = np.ones((3, 3))
print(c)

In [ ]:
d = np.eye(3)
print(d)

In [ ]:
e = np.random.random((3, 3))
print(e)

In [ ]:
f = np.random.randn(3, 3)
print(f)

In [ ]:
np.random.randn()

In [ ]:
print(e)
print(e[1, 1])

In [ ]:
g = np.full((3, 3), 1.5)
print(g)
print(g.dtype)

In [ ]:
a = np.arange(3)
print(a)
print(a.reshape(1, -1))
print(a.reshape(-1, 1))

# slicing

In [ ]:
a = np.arange(1, 13, 1, dtype=np.int32).reshape((3, 4))
print(a)
b = a[:2, :3]
print(b)

In [ ]:
b[0, 0] = 100
print(a)
print(b)

In [ ]:
a = np.arange(1, 13, 1, dtype=np.int32).reshape((3, 4))
b = np.zeros((2, 3), dtype=np.int32)
print(a)
b[:] = a[:2, :3]
print(b)

In [ ]:
b[0, 0] = 100
print(a)
print(b)

https://stackoverflow.com/questions/2612802/list-changes-unexpectedly-after-assignment-why-is-this-and-how-can-i-prevent-it

In [ ]:
a = np.arange(1, 13, 1, dtype=np.int32).reshape((3, 4))
print(a)
b = a[:2, :3].copy()
print(b)

In [ ]:
b[0, 0] = 100
print(a)
print(b)

In [ ]:
print(a)

row_r1 = a[1, :]
row_r2 = a[1:2, :]

print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)

# class

In [71]:
class Dog:
    classcall = 0             # class variable shared by all instances
    def __init__(self, name):
        self.name = name
        Dog.classcall += 1

    def add_trick(self, trick):
        print(trick)

In [ ]:
print(Dog.classcall)
a = Dog('뽀삐')
print(Dog.classcall)
b = Dog('까미')
print(Dog.classcall)

a.add_trick('asdf')
b.add_trick('zxcv')

In [73]:
class FourCal:
    def __init__(self, first, second):
        self.first = first
        self.second = second
    def setdata(self, first, second):
        self.first = first
        self.second = second
    def add(self):
        result = self.first + self.second
        return result
    def mul(self):
        result = self.first * self.second
        return result
    def sub(self):
        result = self.first - self.second
        return result
    def div(self):
        result = self.first / self.second
        return result

In [ ]:
a = FourCal(1, 2)
a.sub()

In [76]:
class hier(FourCal):
  pass

In [77]:
a = hier(3, 4)
a.mul()

12

# Broadcasting

Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.



In [ ]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

# Now y is the following
# [[ 2  2  4]
#  [ 5  5  7]
#  [ 8  8 10]
#  [11 11 13]]
print(y)

In [ ]:
print(x)
print(v)

In [ ]:
x+=v
print(x)